parameters:
    global_container.listener.class: WW\WWGlobalContainerBundle\Listener\GlobalContainerListener

services:
    global_container.listener:
        class: %global_container.listener.class%
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
